[build]
  base = "packages/noirlings"
  command = "NODE_OPTIONS=--max-old-space-size=6144 yarn build:netlify"
  publish = "../../dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.0.2"
  VITE_SUPABASE_URL = "https://ajzoulspsdzrjxffqvoi.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqem91bHNwc2R6cmp4ZmZxdm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDYzMDMsImV4cCI6MjA2Nzg4MjMwM30.iHTW9lmLwlq3nWsz1NYeQJg-ZKYgrOaN6SBMHNyndLg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Disable functions to save memory
  directory = "functions"
  included_files = []